apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    purpose: learning
  annotations:
    description: this deployment is created for learning purposes
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      purpose: learning 
  template:
    metadata:
      labels:
        purpose: learning 
    spec:
      containers:
        - name: my-home-container
          image: abhishekimage/home  
          ports:
            - containerPort: 80 
