apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    purpose: learning
  annotations:
    description: this deployment is created for learning purpose
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      purpose: learning  # This matches the label in the pod template.
  template:
    metadata:
      labels:
        purpose: learning  # This ensures the pods have the correct label.
    spec:
      containers:
        - name: my-home-container
          image: abhishekimage/home
          ports:
            - containerPort: 80
