apiVersion: apps/v1
kind: Deployment 
metadata:
  name: about-deployment
  labels:
    purpose: learning 
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1    
  selector:
    matchLabels:
      purpose: learning 
  template:
    metadata:
      name: about-deployment 
      labels:
        purpose: learning
    spec:
      containers:
        - name: about-pod
          image: abhishekimage/about
          ports:
            - containerPort: 80
          

