apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    team: backend
  annotations:
    description: this deployment is created for learning purposes
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      team: backend
  template:
    metadata:
      labels:
        team: backend
    spec:
      containers:
        - name: my-home-container
          image: abhishekimage/home
          ports:
            - containerPort: 80
