apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    purpose: learning
  annotations:
    description: this deployment is created for learning purposes
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      purpose: learning  # This label must match the label in the pod template
  template:
    metadata:
      labels:
        purpose: learning  # Ensure the pod template has this same label
    spec:
      containers:
        - name: my-home-container
          image: abhishekimage/home  # Ensure the image exists and is accessible
          ports:
            - containerPort: 80  # Exposing port 80 inside the container
