apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    team: backend
    purpose: learning
  annotations:
    description: this deployment is created for learning purpose
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:  
      page: home
  template:
    metadata:
      labels:
        page: home
    spec:
      containers:
        - name: my-home-container
          image: abhishekimage/home
          ports:
            - containerPort: 80 
