apiVersion: v1
kind: Service 
metadata: 
  name: loadBalancer-service
spec:
  selector:
    team: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      
  type: LoadBalancer