apiVersion: v1
kind: Service 
metadata: 
  name: loadbalancer-service
spec:
  selector:
    team: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP  
      port: 8080
      targetPort: 8080

  type: LoadBalancer