apiVersion: v1
kind: Service 
metadata: 
  name: loadbalancer-service
spec:
  selector:
    team: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: api 
      protocol: TCP  
      port: 8080
      targetPort: 80

  type: LoadBalancer