# this is for learning 
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
  labels:
    purpose: learning
    team: backend
  annotations:
    purpose: this is default namespace created for learning features
