apiVersion: v1
kind: Service 
metadata: 
  name: nodeport-service
spec:
  selector:
    purpose: learning
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 8080
      
  type: NodePort